services:
  orders-group-sheet:
    build:
      context: ./
      dockerfile: ./build/package/Dockerfile
    env_file:
      - ./.env
    networks:
      - sisconf_backend_default
  
networks:
  sisconf_backend_default:
    external: true